beacon-biosignals/K8sClusterManagers.jl

Project.toml, README.md, src/K8sClusterManagers.jl
kubectl is no longer required to be running in a side-car container
addresses #6 
This ends up simplifying a couple of other annoyances:
- no need to pass in an `IMAGE` env variable; since there is only one container in the pod, we can default to using the driver container's image for workers by passing `image=nothing` to `addprocs_pod`.
- if the driver is running as a job, that job will complete on exit only if there are no side-cars.
=> use kubectl_jll

src/K8sClusterManagers.jl
Without this check non supported platforms (like Apple Silicon) fail in a non-obvious way:
```julia
julia> using K8sClusterManagers
[ Info: Precompiling K8sClusterManagers [5aeab163-63d2-4171-9fbf-e22244d80acb]
ERROR: InitError: UndefVarError: kubectl not defined
during initialization of module K8sClusterManagers
```
=> Validate kubectl_jll is available

Project.toml, src/native_driver.jl, test/runtests.jl
Addresses part of this comment: https://github.com/beacon-biosignals/K8sClusterManagers.jl/issues/12#issuecomment-804397605
> Fix the double stack trace. I'm not sure why the stack trace was emitted twice here but it's also just adding noise
Here's a quick example when running the cluster manager on my local system. I've removed the stacktraces to make the output shorter.
Without this PR:
```julia
julia> ENV["HOSTNAME"] = "localhost";
julia> K8sClusterManagers.addprocs_pod(1)
[ Info: unsupported events.k8s.io/v1
[ Info: unsupported certificates.k8s.io/v1
[ Info: unsupported node.k8s.io/v1
[ Info: unsupported flowcontrol.apiserver.k8s.io/v1beta1
ERROR: Swagger.ApiException(404, "Not Found", HTTP.Messages.Response:
"""
HTTP/1.1 404 Not Found
Cache-Control: no-cache, private
Content-Length: …
```
=> Address reporting duplicate error messages

Project.toml, src/native_driver.jl, test/runtests.jl
I was just going to store `"default"` as a global constant but after reviewing https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/ I opted for this solution
=> Define `current_namespace` function

src/K8sClusterManagers.jl
As `kubectl` itself doesn't require this proxy to the Kubernetes API server I experimented with removing the proxy entirely and discovered:
```juia
julia> K8sClusterManagers.addprocs_pod(3)
ERROR: IOError(Base.IOError("connect: connection refused (ECONNREFUSED)", -111) during request(http://localhost:8001/api/))
Stacktrace:
[1] wait_connected(::Sockets.TCPSocket) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Sockets/src/Sockets.jl:525
[2] connect at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Sockets/src/Sockets.jl:560 [inlined]
[3] connect(::Sockets.IPv4, ::UInt64) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Sockets/src/Sockets.jl:546
[4] getconnection(::Type{Sockets.TCPSocket}, ::SubString{String}, …
```
=> Add comments for `restart_kubectl_proxy`

Project.toml, src/K8sClusterManagers.jl, src/native_driver.jl, test/runtests.jl
I discovered when reading https://kubernetes.io/docs/tasks/run-application/access-api-from-pod/#without-using-a-proxy that the service account directory inside a pod contains a "namespace" file containing the name of the pod's namespace. This PR means that K8sClusterManagers.jl users no longer need to specify the namespace when running inside of a pod which avoids mistakes which can lead to: https://github.com/beacon-biosignals/K8sClusterManagers.jl/issues/12
=> Determine namespace inside of pod

README.md, src/K8sClusterManagers.jl, src/native_driver.jl, src/pod.jl, test/cluster.jl, test/native_driver.jl, test/pod.jl, test/runtests.jl
Fixes https://github.com/beacon-biosignals/K8sClusterManagers.jl/issues/13
Overview of the changes:
- Renamed `K8sNativeManager` to `K8sClusterManager`.
- Since the `addprocs` function typically handles specifying defaults for `exename` and `exeflags` I needed to move the worker pod spec generation into the `launch` method. Doing this required changes to what was stored within the `K8sClusterManager` struct.
- If a user attempts to launch a k8s cluster without specifying an `image` while running the code outside of a pod an exception will be thrown. This check is now done in the `K8sClusterManager` constructor to avoid having the exception raised inside of a task (how `launch` is called).
- Added a `K8sClusterManager` constructor that takes number of worker to launch
- Stored the pod name …
=> Revise to be inline with Cluster Manager interface

src/native_driver.jl, test/cluster.jl
I noticed the cluster tests had this in the manager log:
```
error in running finalizer: MethodError(f=Distributed.manage, args=(K8sClusterManagers.K8sClusterManager(ports=Array{UInt16, (1,)}[0x2329], driver_name="test-success-t4blj", image="k8s-cluster-managers:faf3fa9-dirty-35684", cpu="1", memory="750M", retry_seconds=60, configure=Main.configure), 2, Distributed.WorkerConfig(io=nothing, host="172.17.0.4", port=9001, count=nothing, exename=nothing, exeflags=nothing, userdata=(pod_name="test-success-t4blj-worker-9001",), tunnel=nothing, multiplex=nothing, forward=nothing, bind_addr="172.17.0.4", sshflags=nothing, max_parallel=nothing, connect_at=("172.17.0.4", 9001), process=nothing, ospid=1, environ=Base.Dict{Any, Any}(slots=Array{UInt8, (16,)}[0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, …
```
=> Define manage for `K8sClusterManager`

src/pod.jl, test/pod.jl
Should assist with manual efforts to terminate all of the workers in a cluster.
=> Add manager label to workers

Project.toml, src/native_driver.jl, src/pod.jl, test/cluster.jl, test/pod-control.yaml, test/runtests.jl
Code changes in place just to support using a generated pod name. Being able to use a unique pod name is important for solving #39. Using a generated pod name will happen in another PR. 
Was originally part of: https://github.com/beacon-biosignals/K8sClusterManagers.jl/pull/41
=> Support `generateName` for worker pods

codecov.yml
It appears that sometimes codecov doesn't update the comment to reflect the current coverage status. This behaviour should make it more obvious if the comment has been updated as the old comment will be deleted and a new one posted.
=> Change Codecov comment behaviour

src/native_driver.jl, src/pod.jl, test/cluster.jl, test/pod-control.yaml, test/pod.jl, test/runtests.jl
Since we've removed Kuber.jl we no longer need to have special logic to handle API throttling exceptions. This overall has allowed the `Distributed.launch` method to be much cleaner.
Also, I fixed an issue with the reporting in the "test-multi-addprocs" test.
=> Refactor `Distributed.launch`

src/native_driver.jl, test/cluster.jl
The name `retry_seconds` hasn't made much sense since retries were removed in #47. In #50 I changed the waiting behaviour to only timeout while waiting for a pending pod so now is the time change the keyword name.
=> Rename `retry_seconds` to `pending_timeout`

src/native_driver.jl, src/pod.jl, test/cluster.jl, test/pod.jl, test/runtests.jl
Fixes https://github.com/beacon-biosignals/K8sClusterManagers.jl/issues/15. If a worker fails for any reason we now will report the termination reason specified by Kubernetes. This should be useful for cluster users by providing them a basic reason as to why their worker was terminated. Specifically this feature was added to inform users of workers being terminated due to running into memory limits (OOM).
=> Report abnormal worker terminations

src/K8sClusterManagers.jl, src/native_driver.jl, test/cluster.jl, test/job.template.yaml
Addresses: https://github.com/beacon-biosignals/K8sClusterManagers.jl/issues/56
=> Redirect worker output via `kubectl logs -f`

docs/Project.toml, docs/make.jl
May fix #64. I noticed in the [Documenter CI job](https://github.com/beacon-biosignals/K8sClusterManagers.jl/runs/2470780970?check_suite_focus=true) that `GITHUB_TOKEN` wasn't listed which may be because we are using an old version of Documenter.jl:
```
┌ Info: Deployment criteria:
│ - ✔ ENV["TRAVIS_REPO_SLUG"]="" occurs in repo="github.com/beacon-biosignals/K8sClusterManagers.jl.git"
│ - ✘ ENV["TRAVIS_PULL_REQUEST"]="" is "false"
│ - ✔ ENV["TRAVIS_TAG"]="" is (i) empty or (ii) a valid VersionNumber
│ - ✘ ENV["TRAVIS_BRANCH"]="" matches devbranch="main" (if tag is empty)
│ - ✔ ENV["DOCUMENTER_KEY"] exists
│ - ✔ ENV["TRAVIS_EVENT_TYPE"]="" is not "cron"
└ Deploying: ✘
=> Update Documenter to 0.26

.github/workflows/CI.yml
As mentioned in: https://github.com/codecov/codecov-action , codecov-action@v1 will be deprecated/sunset on February 1, 2022.
There are a few breaking changes mentioned in the codecov-action README.md, but I don't think this workflow uses any of the breaking changes mentioned.
=> Update CI codecov-action v2

.github/workflows/CI.yml, test/cluster.jl, test/job.template.yaml, test/utils.jl
When running the cluster integration tests I was seeing issues with errors such as resource "NotFound". This turned out to be that the job TTL was cleaning up resources before the tests validated the results. I've since switched to deleting the resources manually to avoid such a scenario. This also as the added benefit of removing resources immediately when tests pass.
Additionally, having users specify `eval $(minikube docker-env)` before running the tests is easy to miss so I added some code to do that for the user.
=> Updates to cluster tests

test/cluster.jl, test/job.template.yaml, test/pod-control.yaml
When the cluster tests encounter failure we avoid deleting the resources which failed in order to facilitate investigations. Unfortunately, cleaning up after failures can be rather tedious so I decided to add this common label to all resources created by these tests to make it easy to delete all created K8s resources via:
```sh
kubectl delete pod,job,sa,role,rolebinding -l origin=k8s-cluster-manager-tests
```
=> Add a common test label to created resources

codecov.yml
Trying to reduce noise from Codecov which always reports that coverage has dropped as our unit tests finish far earlier than our cluster tests.
e.g.
=> Use Codecov `after_n_builds`

Project.toml, src/pod.jl, test/cluster.jl, test/pod.jl
Noticed this `isk8s` function no longer works on the latest version of Kubernetes. I've refactored this function to work on modern versions and have added some in-cluster tests to ensure this isn't missed again if this functionality breaks again.
=> Refactor `isk8s`

src/native_driver.jl, test/native_driver.jl
The `HOSTNAME` environmental variable does seem to always be set when running in a K8s pod but other environments should use `gethostname` to determine the hostname.
=> Use `gethostname` to determine pod name

test/cluster.jl, test/job.template.yaml, test/pod-control.yaml
Follow up to #98. Makes it easier to update the common test labels in Julia code and also changes the label used (the "origin" label was attempting to be too generic).
=> Refactor common test resource labels

src/native_driver.jl, src/pod.jl, test/cluster.jl, test/native_driver.jl, test/pod.jl
Allows end users to customize the prefix assigned to worker names while still begin able to look up the image of a manager pod. I did like how workers were assigned the name of their manager via labels in the old code but in the new world where we have managers which are external to the cluster this seems more sensible.
=> Separate keywords `worker_prefix` and `manager_pod_name`

Project.toml, README.md, docs/src/examples.md, src/K8sClusterManagers.jl, src/native_driver.jl, test/cluster.jl, test/utils.jl
Replaces #94. Adds support for having the Julia cluster manager running externally from the workers running inside a cluster while retaining support for in-cluster managers. 
Julia's Distributed package isn't well suited for the heterogeneous network connections we're using here so I was forced to extend the `Distributed.connect` function and modify it's behaviour for this particular cluster manager. In particular manager-to-worker connections need to use the special port-forwarded addresses while workers can continue to use intra cluster network connections. 
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204267974135853
=> Support managers external to K8s clusters
