- .github/workflows/TagBot.yml
- .travis.yml
- README.md
- docs/Project.toml
- docs/make.jl
> Add TagBot + travis build/docs + badges

- LICENSE.md
> Use correct package name in LICENSE

- .github/workflows/CI.yml
- Project.toml
- src/K8sClusterManagers.jl
> Set compat for all dependencies

- Project.toml
- src/K8sClusterManagers.jl
- src/native_driver.jl
> Use `time()` for duration calculations

- src/K8sClusterManagers.jl
> Refactor KUBECTL_PROXY_PROCESS

- src/native_driver.jl
> Generate JSON with Julia dicts

- test/cluster.jl
- test/job.template.yaml
> Use pod `args` instead of just `command`

- src/pod.jl
- test/native_driver.jl
- test/pod.jl
> Drop unused `self_pod` function

- .github/workflows/CI.yml
> Update Minikube GHA

- test/cluster.jl
- test/runtests.jl
- test/utils.jl
Refactor cluster tests to allow for better re-use. This should make it easier to add additional tests.
Was originally part of: #41
> Add cluster test utilities

- src/native_driver.jl
- src/pod.jl
- test/cluster.jl
- test/job.template.yaml
- test/runtests.jl
- test/utils.jl
Adds the Julia worker ID (`myid`) as a label to the Kubernetes worker pod. Mainly this is just for convenience but it should make some debugging easier.
> Label workers with the Julia worker ID

- src/native_driver.jl
- src/pod.jl
- test/cluster.jl
- test/job.template.yaml
- test/runtests.jl
The `K8sClusterManager` now handles the process interruption.
> Support interrupting workers

- src/pod.jl
- test/pod.jl
In a scenario where a pod's container fails immediately we could end up waiting the full timeout duration for the pod to reach the "Running" phase. This PR changes the behaviour to only wait while in the "Pending" phase and use a separate error message if the pod skips the "Running" phase entirely.
> Avoid waiting for timeout when pod fails

- Project.toml
Looks like this was missed in #34
> Add compat for DataStructures

- src/native_driver.jl
- test/native_driver.jl
Makes the included JSON print nicely
> Add `showerror` method for `TimeoutException`

- src/native_driver.jl
- test/cluster.jl
- test/job.template.yaml
Now actually follows the documentation as specified in `pending_timeout`
> Launch proceeds if pending timeout is reached

- README.md
- docs/Project.toml
- docs/make.jl
- docs/src/api.md
- docs/src/examples.md
- docs/src/index.md
- docs/src/interactive-session.yaml
- docs/src/julia-manager-serviceaccount.yaml
- docs/src/patterns.md
- src/pod.jl
Closes https://github.com/beacon-biosignals/K8sClusterManagers.jl/issues/4
> Documentation patterns with K8sClusterManagers

- .github/workflows/CI.yml
Proposed fix for: https://github.com/beacon-biosignals/K8sClusterManagers.jl/issues/74
> Run CI on tags

- .github/workflows/CI.yml
- Dockerfile
- test/job.template.yaml
Fixes: https://github.com/beacon-biosignals/K8sClusterManagers.jl/issues/82
> Fix "Cluster Test" CI job

- .github/workflows/CI.yml
- Project.toml
- src/namespace.jl
- src/native_driver.jl
- src/pod.jl
- test/cluster.jl
- test/namespace.jl
- test/utils.jl
I ran into essentially the same issue as https://discourse.julialang.org/t/ioerror-could-not-spawn-argument-list-too-long/43728/12
when launching 20 workers.
> Use thread-safe executable product call

- .github/workflows/CI.yml
> Update GitHub action dependencies
